name: buildQA
run-name: ${{ github.actor }} is running STAGING build workflow
on:
    pull_request:
        types:
        - closed
        branches:
        - main
jobs:
    build:
        if: github.event.pull_request.merged == true
        uses: ivzeus/sample-firebase-app/.github/workflows/build.yml@main
        with:
            FORCE_UPLOAD: true
        secrets: inherit

    deploy:
        if: github.event.pull_request.merged == true
        needs: [build]
        uses: ivzeus/sample-firebase-app/.github/workflows/deploy.yml@main
        with:
            PROJECT: ${{ vars.STAGING_GKE_PROJECT }}
            CLUSTER: ${{ vars.STAGING_GKE_CLUSTER }}
            ZONE: ${{ vars.STAGING_GKE_ZONE }}
            DEPLOYMENT: ${{ vars.STAGING_GKE_DEPLOYMENT }}
        secrets: inherit