name: manual-build
run-name: ${{ github.actor }} is running manual build workflow
on:
  workflow_dispatch:
    inputs:
      FORCE_UPLOAD:
        required: true
        type: boolean
        default: false
jobs:
  init:
    runs-on: ubuntu-latest
    outputs:
      IMAGE: "${{ vars.GKE_IMAGE }}-${{ github.ref_name }}.${{ github.sha }}"
      BUILD_SIGNATURE: "${{github.run_id}}-${{ github.ref_name }}.${{ github.sha }}"
    steps:
      - run: echo "Build docker image with tag ${{ vars.GKE_IMAGE }}-${{ github.ref_name }}.${{ github.sha }}"
      - run: echo "Build signature ${{ github.ref_name }}.${{ github.sha }}"
      - run: echo "Login to GKE credential ${{ secrets.GKE_CREDENTIALS }}"
      - run: echo "Upload build to ${{ vars.GKE_REPO }}"

  build:
    if: inputs.FORCE_UPLOAD
    needs: [init]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.sha }}
      - run: echo "${{ needs.init.outputs.BUILD_SIGNATURE }}" > ./server/_buildSignature.txt
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to GAR
        uses: docker/login-action@v2
        with:
          registry: ${{ vars.GKE_REGISTRY }}
          username: _json_key
          password: ${{ secrets.GKE_CREDENTIALS }}
      - name: Login to gcloud cli
        uses: "google-github-actions/auth@v1"
        with:
          credentials_json: ${{ secrets.GKE_CREDENTIALS }}
      - run: gcloud auth configure-docker ${{ vars.GKE_REGISTRY }}
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          file: DockerKube.dockerfile
          tags: ${{ vars.GKE_REPO }}/firebase-app:latest
